name: crop-yield-estimate-env
dependencies:
  - python=3.10.*
  - pip
  - pip:
      - jupyter
      - scikit-learn
      - wandb
      - pandas
      - numpy
      - GPUtil
      - plotly
      - matplotlib
      - xgboost
      - lightgbm
      - catboost
      - lcensemble
      - verstack
#      - pytorch-tabnet