name: crop-yield-estimate-env
dependencies:
  - python=3.10.*
  - pip
  - pip:
      - jupyter
      - scikit-learn==1.2
      - wandb
      - pandas
      - numpy
      - GPUtil
      - plotly
      - matplotlib
      - xgboost
      - lightgbm
      - catboost
      - umap-learn
      - be-great
      - imbalanced-learn      
