colsample_bylevel:
  value: 0.26920740806843446

colsample_bynode:
  value: 0.840736071896449

colsample_bytree:
  value: 0.2729381050313101

cv:
  value: 5

delna_thr:
  value: 0.6330754857432224

estimator_name:
  value: "XGBoost"

eval_metric:
  value: "logloss"

fillna:
  value: true

gamma:
  value: 7.157743571689607

generated_file:
  value: "TrainGenerated-6038.csv"

great_augmentation:
  value: true

learning_rate:
  value: 0.6427068091075152

limit_h:
  value: 5000

limit_l:
  value: 500

max_depth:
  value: 3

max_target_by_acre:
  value: "none"

min_child_weight:
  value: 3.95564392051145

n_estimators:
  value: 276

random_state:
  value: 42

reg_alpha:
  value: 21.35569543418578

reg_lambda:
  value: 20.72196075591198

scale:
  value: "none"

smote_augmentation:
  value: false

subsample:
  value: 0.21286349842483931

task:
  value: "classification"

use_llm_imputation:
  value: false