random_state:
  value: 42

cv:
  value: 5

task:
  value: 'classification'

limit_h:
  value: 5000

limit_l:
  value: 500

use_llm_imputation:
  value: True

smote_augmentation:
  value: True

great_augmentation:
  value: True

generated_file:
  value: 'TrainGenerated-6038.csv'

max_target_by_acre:
  value: 25000

# Preprocessing
delna_thr:
  value: 0.5

fillna:
  value: True

scale:
  value: 'none'

# Model
estimator_name:
  value: 'LightGBM'

num_leaves:
  value: 128

max_depth:
  value: 8

learning_rate:
  value: 0.5

n_estimators:
  value: 500

class_weight:
  value: 'balanced'

min_child_samples:
  value: 50

subsample: # bagging_fraction
  value: 0.5

colsample_bytree: # feature_fraction
  value: 0.5

reg_alpha:
  value: 5

reg_lambda:
  value: 5

verbose:
  value: -1