# General
method: bayes

metric:
  name: rmse/avg
  goal: minimize

parameters:
  random_state:
    distribution: constant
    value: 42

  cv:
    distribution: constant
    value: 5

  # Preprocessing
  target_name:
    distribution: constant
    value: 'Yield'

  delna_thr:
    distribution: uniform
    min: 0
    max: 1

  fill_mode:
    distribution: categorical
    values: [ 'none', 'median', 'mean' ]

  normalisation:
    distribution: categorical
    values: [ True, False ]

  # Model


