# General
method: bayes

metric:
  name: rmse/avg
  goal: minimize

parameters:
  random_state:
    distribution: constant
    value: 42

  cv:
    distribution: constant
    value: 5

  # Preprocessing
  target_name:
    distribution: constant
    value: 'Yield'

  delna_thr:
    distribution: uniform
    min: 0
    max: 1

  fill_mode:
    distribution: categorical
    values: [ 'none', 'median', 'mean' ]

  normalisation:
    distribution: categorical
    values: [ True, False ]

  # Model
  boosting_type:
    distribution: categorical
    values: [ 'gbdt', 'dart', 'rf' ]

  num_leaves:
    distribution: int_uniform
    min: 10
    max: 1000

  max_depth:
    distribution: int_uniform
    min: -1
    max: 100

  learning_rate:
    distribution: uniform
    min: 0.01
    max: 0.5

  n_estimators:
    distribution: int_uniform
    min: 50
    max: 1000

  subsample_for_bin:
    distribution: int_uniform
    min: 100000
    max: 300000

  min_split_gain:
    distribution: uniform
    min: 0
    max: 1

  min_child_weight:
    distribution: uniform
    min: 0.001
    max: 1

  min_child_samples:
    distribution: int_uniform
    min: 10
    max: 100

  subsample:
    distribution: uniform
    min: 0.5
    max: 1

  subsample_freq:
    distribution: uniform
    min: 0.5
    max: 1

  colsample_bytree:
    distribution: uniform
    min: 0.5
    max: 1

  reg_alpha:
    distribution: uniform
    min: 0
    max: 1

  reg_lambda:
    distribution: uniform
    min: 0
    max: 1

