# General
method: bayes

metric:
  name: rmse/avg
  goal: minimize

parameters:
  random_state:
    distribution: constant
    value: 42

  cv:
    distribution: constant
    value: 5

  # Preprocessing
  target_name:
    distribution: constant
    value: 'Yield'

  delna_thr:
    distribution: uniform
    min: 0
    max: 1

  fill_mode:
    distribution: categorical
    values: [ 'none', 'median', 'mean' ]

  normalisation:
    distribution: categorical
    values: [ True, False ]

  # Model
  estimator_name:
    distribution: constant
    value: 'XGBoost'

  n_estimators:
    distribution: int_uniform
    min: 50
    max: 1000

  max_depth:
    distribution: int_uniform
    min: 2
    max: 100

  max_leaves:
    distribution: int_uniform
    min: 0
    max: 100

  max_bin:
    distribution: int_uniform
    min: 2
    max: 255

  grow_policy:
    distribution: categorical
    values: [ 'depthwise', 'lossguide' ]

  learning_rate:
    distribution: uniform
    min: 0.01
    max: 0.5

  booster:
    distribution: categorical
    values: [ 'gbtree', 'gblinear', 'dart' ]

  tree_method:
    distribution: categorical
    values: [ 'auto', 'exact', 'approx', 'hist' ]

  gamma:
    distribution: uniform
    min: 0
    max: 10

  min_child_weight:
    distribution: uniform
    min: 1
    max: 100

  max_delta_step:
    distribution: uniform
    min: 0
    max: 10

  subsample:
    distribution: uniform
    min: 0.5
    max: 1

  colsample_bytree:
    distribution: uniform
    min: 0.5
    max: 1

  colsample_bylevel:
    distribution: uniform
    min: 0.5
    max: 1

  colsample_bynode:
    distribution: uniform
    min: 0.5
    max: 1

  reg_alpha:
    distribution: uniform
    min: 0
    max: 5

  reg_lambda:
    distribution: uniform
    min: 0
    max: 5

  scale_pos_weight:
    distribution: uniform
    min: 0
    max: 10

