# General
method: bayes

metric:
  name: reg/rmse
  goal: minimize

parameters:
  random_state:
    distribution: constant
    value: 42

  cv:
    distribution: constant
    value: 5

  task:
    distribution: constant
    value: 'regression'

  # Preprocessing
  delna_thr:
    distribution: uniform
    min: 0
    max: 1

  fillna:
    distribution: categorical
    values: [True, False]

  # Model
  estimator_name:
    distribution: constant
    value: 'LCE'

  n_estimators:
    distribution: int_uniform
    min: 50
    max: 1000

  max_depth:
    distribution: int_uniform
    min: 2
    max: 100

  max_features:
    distribution: uniform
    min: 0
    max: 1

  max_samples:
    distribution: uniform
    min: 0
    max: 1

  min_samples_leaf:
    distribution: uniform
    min: 0
    max: 1

  n_iter:
    distribution: int_uniform
    min: 10
    max: 100

  base_learner:
    distribution: categorical
    values: [ 'catboost', 'lightgbm', 'xgboost' ]

  base_n_estimators:
    distribution: int_uniform
    min: 50
    max: 1000

  base_max_depth:
    distribution: int_uniform
    min: 2
    max: 100

  base_num_leaves:
    distribution: int_uniform
    min: 1
    max: 100

  base_learning_rate:
    distribution: uniform
    min: 0.01
    max: 0.5

  base_booster:
    distribution: categorical
    values: [ 'dart', 'gblinear', 'gbtree' ]

  base_boosting_type:
    distribution: categorical
    values: [ 'dart', 'gbdt', 'rf' ]

  base_gamma:
    distribution: uniform
    min: 0
    max: 10

  base_min_child_weight:
    distribution: uniform
    min: 0
    max: 1000

  base_subsample:
    distribution: uniform
    min: 0.5
    max: 1

  base_subsample_for_bin:
    distribution: int_uniform
    min: 100000
    max: 300000

  base_colsample_bytree:
    distribution: uniform
    min: 0.5
    max: 1

  base_colsample_bylevel:
    distribution: uniform
    min: 0.5
    max: 1

  base_colsample_bynode:
    distribution: uniform
    min: 0.5
    max: 1

  base_reg_alpha:
    distribution: uniform
    min: 0
    max: 100

  base_reg_lambda:
    distribution: uniform
    min: 0
    max: 100


