# General
method: bayes

metric:
  name: reg/rmse
  goal: minimize

parameters:
  random_state:
    distribution: constant
    value: 42

  cv:
    distribution: constant
    value: 5

  task:
    distribution: constant
    value: 'regression'

  limit_h:
    distribution: constant
    value: 5000

  limit_l:
    distribution: constant
    value: 500

  # Preprocessing
  delna_thr:
    distribution: uniform
    min: 0
    max: 1

  fillna:
    distribution: categorical
    values: [True, False]

  scale:
    distribution: categorical
    values: [ 'none', 'Acre', 'CultLand', 'CropCultLand' ]

  # Model
  estimator_name:
    distribution: constant
    value: 'XGBoost'

  eval_metric:
    distribution: constant
    value: 'rmse'

  n_estimators:
    distribution: int_uniform
    min: 100
    max: 1000

  learning_rate:
    distribution: uniform
    min: 0
    max: 1

  max_depth:
    distribution: int_uniform
    min: 1
    max: 100

  subsample:
    distribution: uniform
    min: 0
    max: 1

  colsample_bytree:
    distribution: uniform
    min: 0
    max: 1

  colsample_bylevel:
    distribution: uniform
    min: 0
    max: 1

  colsample_bynode:
    distribution: uniform
    min: 0
    max: 1

  min_child_weight:
    distribution: uniform
    min: 1
    max: 5

  reg_alpha:
    distribution: uniform
    min: 0
    max: 50

  reg_lambda:
    distribution: uniform
    min: 0
    max: 50

  gamma:
    distribution: uniform
    min: 0
    max: 10


